### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [sjelfull/Craft-Randomm#1]

**Comment by sjelfull** [comment]
@arenrey Hey, sorry for the late reply. Currently the random strings are generated by chance.js, which is only clientside. I've been looking into PHP alternatives that might be worthy alternatives, but haven't found anything great yet. Any suggestions?

**Comment by sjelfull** [comment]
Thanks for looking, @arenrey. Sorry to say, that only generates random numbers, while chance.js have a multitude of options.

https://github.com/fzaninotto/Faker is more what we're looking for, but from the looks of it, it doesn't have all the options, so I wonder what is the best way to proceed.

I might add it in, and make a note about the differences. After all, not many are using the plugin yet, so possible confusion doesn't bother me that much.
